# Generated by Django 4.0.2 on 2023-11-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pac', '0002_alter_activity_latitude_alter_activity_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('activities', models.ManyToManyField(related_name='activity_photos', to='pac.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.ManyToManyField(related_name='activity_photos', to='pac.Photo'),
        ),
    ]
