# Generated by Django 4.0.2 on 2023-11-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0004_alter_activity_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='image_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='activities',
        ),
        migrations.AddField(
            model_name='photo',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.activity'),
        ),
    ]
