# Generated by Django 4.0.1 on 2022-02-14 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0002_delete_spiuprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district_id',
            field=models.OneToOneField(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistricts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district_incharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='district_incharge_designation',
            field=models.CharField(blank=True, choices=[('AD', 'Assistant Director'), ('DD', 'Deputy Director')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnic',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_disclaimer_agreed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
