# Generated by Django 4.0.2 on 2023-12-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiu', '0002_profile_district_id_profile_district_incharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('-', 'Rather not say')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
