# Generated by Django 4.0.2 on 2024-01-04 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0014_gpsdata_alter_poultryfarms_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_industry', models.CharField(max_length=254, verbose_name='Name of Industry')),
                ('address_industry', models.CharField(max_length=354, verbose_name='Address of Industry')),
                ('latitude', models.FloatField(help_text='up to 6 decimals between 25 to 40', verbose_name='latitude of sample location')),
                ('longitude', models.FloatField(help_text='up to 6 decimals between 60 to 80', verbose_name='longitude of sample location')),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pim.projectsubcategory', verbose_name='Industrial Category')),
                ('tehsil_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbltehsils', verbose_name='Name of Tehsil from Address')),
            ],
            options={
                'managed': True,
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
