# Generated by Django 4.0.2 on 2023-06-17 18:34

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WwtpDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('wwtp_type', models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], max_length=255, null=True, verbose_name='WWTP Type')),
                ('remarks', models.CharField(blank=True, help_text='Write extra info, if any', max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Check if all information is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('photo1_path', models.FileField(blank=True, help_text='Attach Zoom Photo of Plant', null=True, upload_to='wwtp_photo', verbose_name='Photo-1')),
                ('photo2_path', models.FileField(blank=True, help_text='Attach plant photo covering its surrounding', null=True, upload_to='wwtp_photo', verbose_name='Photo-2')),
                ('latitude', models.FloatField(help_text='up to 6 decimals between 25 to 40', verbose_name='latitude')),
                ('longitude', models.FloatField(help_text='up to 6 decimals between 60 to 80', verbose_name='longitude')),
            ],
            options={
                'db_table': 'wwtp_detail',
                'managed': False,
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
