# Generated by Django 4.0.2 on 2024-03-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=256, verbose_name='Scheme Name')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('approved_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Approved Cost')),
                ('upload_pc1_pdf', models.FileField(blank=True, null=True, upload_to='pc1_pdfs/', verbose_name='Upload PC-I PDF File')),
                ('upload_pc1_word', models.FileField(blank=True, null=True, upload_to='pc1_word/', verbose_name='Upload PC-I Word File')),
                ('upload_revised_pc1_pdf', models.FileField(blank=True, null=True, upload_to='revised_pc1_pdfs/', verbose_name='Upload Revised PC-I PDF')),
                ('upload_revised_pc1_word', models.FileField(blank=True, null=True, upload_to='revised_pc1_word/', verbose_name='Upload Revised PC-I Word')),
                ('ddsc_date', models.DateField(blank=True, null=True, verbose_name='DDSC Date')),
                ('upload_ddsc_meeting_notice', models.FileField(blank=True, null=True, upload_to='ddsc_meeting_notices/', verbose_name='Upload DDSC Meeting Notice')),
                ('ddsc_mom_issue_date', models.DateField(blank=True, null=True, verbose_name='DDSC Minute of Meeting Issue Date')),
                ('upload_ddsc_mom', models.FileField(blank=True, null=True, upload_to='ddsc_moms/', verbose_name='Upload DDSC Minute of Meeting (PDF)')),
                ('revised_ddsc_date', models.DateField(blank=True, null=True, verbose_name='Revised DDSC Date')),
                ('revised_upload_ddsc_meeting_notice', models.FileField(blank=True, null=True, upload_to='revised_ddsc_meeting_notices/', verbose_name='Upload Revised DDSC Meeting Notice')),
                ('revised_ddsc_mom_issue_date', models.DateField(blank=True, null=True, verbose_name='Revised DDSC MOM Issue Date')),
                ('upload_revised_ddsc_mom', models.FileField(blank=True, null=True, upload_to='ddsc_moms/', verbose_name='Upload Revised DDSC MOM (PDF FIle)')),
                ('tendered_date', models.DateField(blank=True, null=True, verbose_name='Tended Date')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='Award Date')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_progress_date', models.DateField(verbose_name='Physical Progress Date')),
                ('physical_progress_remarks', models.TextField(verbose_name='Physical Progress Remarks')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imar.schemedetail')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
