# Generated by Django 4.0.2 on 2024-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemedetail',
            name='aa_date',
            field=models.DateField(blank=True, null=True, verbose_name='Administrative Approval Date'),
        ),
        migrations.AddField(
            model_name='schemedetail',
            name='gestation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gestation End Date'),
        ),
        migrations.AddField(
            model_name='schemedetail',
            name='gestation_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gestation Start Date'),
        ),
        migrations.AddField(
            model_name='schemedetail',
            name='upload_aa',
            field=models.FileField(blank=True, null=True, upload_to='administrative_approval/', verbose_name='Upload Administrative Approval'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_pc1_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pc1_pdfs/', verbose_name='Upload PC-I (PDF File)'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_pc1_word',
            field=models.FileField(blank=True, null=True, upload_to='pc1_word/', verbose_name='Upload PC-I (Word File)'),
        ),
    ]
