# Generated by Django 4.0.2 on 2024-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imar', '0002_schemedetail_aa_date_schemedetail_gestation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemedetail',
            name='approval_status',
            field=models.BooleanField(default=False, verbose_name='Approval Status'),
        ),
    ]
