# Generated by Django 4.0.2 on 2024-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imar', '0003_schemedetail_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprogress',
            name='physical_progress_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Physical Progress Remarks'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='approved_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Cost'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='revised_upload_ddsc_meeting_notice',
            field=models.FileField(blank=True, null=True, upload_to='imar/revised_ddsc_meeting_notices/', verbose_name='Upload Revised DDSC Meeting Notice'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_aa',
            field=models.FileField(blank=True, null=True, upload_to='imar/aa/', verbose_name='Upload Administrative Approval'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_ddsc_meeting_notice',
            field=models.FileField(blank=True, null=True, upload_to='imar/ddsc_meeting_notices/', verbose_name='Upload DDSC Meeting Notice'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_ddsc_mom',
            field=models.FileField(blank=True, null=True, upload_to='imar/ddsc_moms/', verbose_name='Upload DDSC Minute of Meeting (PDF)'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_pc1_pdf',
            field=models.FileField(blank=True, null=True, upload_to='imar/pc1_pdfs/', verbose_name='Upload PC-I (PDF File)'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_pc1_word',
            field=models.FileField(blank=True, null=True, upload_to='imar/pc1_word/', verbose_name='Upload PC-I (Word File)'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_revised_ddsc_mom',
            field=models.FileField(blank=True, null=True, upload_to='imar/ddsc_moms/', verbose_name='Upload Revised DDSC MOM (PDF FIle)'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_revised_pc1_pdf',
            field=models.FileField(blank=True, null=True, upload_to='imar/revised_pc1_pdfs/', verbose_name='Upload Revised PC-I PDF'),
        ),
        migrations.AlterField(
            model_name='schemedetail',
            name='upload_revised_pc1_word',
            field=models.FileField(blank=True, null=True, upload_to='imar/revised_pc1_word/', verbose_name='Upload Revised PC-I Word'),
        ),
    ]
