# Generated by Django 4.0.2 on 2023-09-13 20:16

from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spiu_gis', '0014_gpsdata_alter_poultryfarms_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrsComplaintsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(max_length=255)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_mobile', models.CharField(max_length=255)),
                ('complainant_address', models.CharField(max_length=255)),
                ('complaint_source', models.CharField(choices=[('PMDU', 'PMDU'), ('DC Office', 'DC Office'), ('MC', 'MC'), ('By hand EPD/Head office', 'By hand EPD/Head office'), ('Receive at EPD+PMDU', 'Receive at EPD+PMDU'), ('Ombudsman', 'Ombudsman'), ('any other source', 'any other source')], max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(help_text='up to 6 decimals between 25 to 40', verbose_name='unit_latitude')),
                ('longitude', models.FloatField(help_text='up to 6 decimals between 60 to 80', verbose_name='unit_longitude')),
                ('air_pollution', models.BooleanField(default=False)),
                ('noise_pollution', models.BooleanField(default=False)),
                ('hazardous_waste', models.BooleanField(default=False)),
                ('municipal_solid_waste', models.BooleanField(default=False)),
                ('noc_cancellation', models.BooleanField(default=False)),
                ('operation_without_noc', models.BooleanField(default=False)),
                ('untreated_waste_water', models.BooleanField(default=False)),
                ('sub_standard_fuel', models.BooleanField(default=False)),
                ('soil_pollution', models.BooleanField(default=False)),
                ('land_degradation', models.BooleanField(default=False)),
                ('other_issue', models.BooleanField(default=False)),
                ('preliminary_examination', models.BooleanField(default=False)),
                ('hearing_notice_issued', models.BooleanField(default=False)),
                ('hearing_notice_date', models.DateField(blank=True, null=True)),
                ('smr_issued', models.BooleanField(default=False)),
                ('smr_date', models.DateField(blank=True, null=True)),
                ('epo_issued', models.BooleanField(default=False)),
                ('epo_date', models.DateField(blank=True, null=True)),
                ('under_trial', models.BooleanField(default=False)),
                ('final_decision', models.BooleanField(default=False)),
                ('sealed', models.BooleanField(default=False)),
                ('desealed', models.BooleanField(default=False)),
                ('firs_arrested', models.BooleanField(default=False)),
                ('complaint_resolved', models.BooleanField(default=False)),
                ('fine_court_or_staff', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistricts')),
            ],
            options={
                'db_table': 'crs_complaints_detail',
                'managed': True,
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
