# Generated by Django 4.0.1 on 2022-02-11 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiuProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=32, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disclaimer_agreed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spiu_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDistricts',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=254)),
                ('district_code', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'tbl_districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDivisions',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=254)),
                ('division_code', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'tbl_divisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPoultryFarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('times_tamp', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('district_incharge', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('name_entry_person', models.CharField(blank=True, max_length=255, null=True)),
                ('name_poultry_farm', models.CharField(blank=True, max_length=255, null=True)),
                ('type_poultry_farm', models.CharField(blank=True, max_length=255, null=True)),
                ('area_poultry_farm', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('environmental_approval_obtained', models.CharField(blank=True, max_length=255, null=True)),
                ('environmental_approval_date', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Poultry Farms',
                'db_table': 'tbl_poultry_farms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTehsils',
            fields=[
                ('tehsil_id', models.AutoField(primary_key=True, serialize=False)),
                ('tehsil_name', models.CharField(max_length=254)),
                ('tehsil_code', models.CharField(max_length=254, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('extent', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'tbl_tehsils',
                'managed': False,
            },
        ),
    ]
