# Generated by Django 4.0.1 on 2022-02-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpiuProfile',
        ),
    ]
