# Generated by Django 4.0.2 on 2022-02-20 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiu_gis', '0003_alter_tbldistricts_options_tblindustrymaincategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultryfarms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poultryfarms',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poultryfarms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='poultryfarms',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
