# Generated by Django 4.0.2 on 2022-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0004_poultryfarms_created_at_poultryfarms_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poultryfarms',
            options={'managed': True, 'verbose_name_plural': 'Poultry Farms'},
        ),
        migrations.AlterModelOptions(
            name='tbldistricts',
            options={'managed': False, 'ordering': (['district_name'],), 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='tbldistrictsincharge',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'District Officers Detail'},
        ),
        migrations.AlterModelOptions(
            name='tblindustrycategory',
            options={'managed': True, 'ordering': (['name'],), 'verbose_name_plural': 'Industry Category'},
        ),
        migrations.AlterModelOptions(
            name='tblindustrymaincategory',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'Industry Main Category'},
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='approval_operational_phase',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Process', 'Under Process')], help_text='Environmental Approval for Section 12 of PEPA (amended 2012) Operation Phase Obtained, Date (if Yes, then provide the following date)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='operational_phase_approval_date',
            field=models.DateField(blank=True, help_text='operationla phase approval date or in case of under process enter application date', null=True),
        ),
    ]
