# Generated by Django 4.0.2 on 2022-02-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0005_alter_poultryfarms_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblindustrycategory',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'Industry Category'},
        ),
        migrations.RenameField(
            model_name='poultryfarms',
            old_name='district',
            new_name='district_id',
        ),
        migrations.RemoveField(
            model_name='tbldistrictsincharge',
            name='district',
        ),
        migrations.AddField(
            model_name='tbldistrictsincharge',
            name='district_id',
            field=models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='spiu_gis.tbldistricts'),
        ),
    ]
