# Generated by Django 4.0.2 on 2022-02-26 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0006_alter_tblindustrycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbldistricts',
            options={'managed': False, 'ordering': ['district_name'], 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='area_poultry_farm',
            field=models.FloatField(blank=True, null=True, verbose_name='Area in Kanals'),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistricts', verbose_name='Name of District'),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='district_incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistrictsincharge', verbose_name='Name of District Incharge'),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude in Decimal Degree format upto 6 decimals like XX.XXXXXX, value would be between 25 to 40', null=True),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude in Decimal Degree format upto 6 decimals like XX.XXXXXX, value would be between 60 to 80', null=True),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='name_poultry_farm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Poultry Farm/ Control Shed'),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Owner'),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='type_poultry_farm',
            field=models.CharField(blank=True, choices=[('Broiler', 'Broiler'), ('Layer', 'Layer'), ('Parent Stock', 'Parent Stock'), ('Grand Parent Stock', 'Grand Parent Stock')], max_length=255, null=True, verbose_name='Type of Poultry Farm / Control Shed'),
        ),
    ]
