# Generated by Django 4.0.2 on 2022-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0007_alter_tbldistricts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultryfarms',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
