# Generated by Django 4.0.2 on 2022-03-13 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0008_poultryfarms_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poultryfarms',
            name='approval_construction_phase',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Process', 'Under Process')], help_text='Environmental Approval for Construction Phase Obtained?, Date (if Yes, then provide the following date)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poultryfarms',
            name='approval_operational_phase',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Process', 'Under Process')], help_text='Environmental Approval for Operation Phase Obtained, Date (if Yes, then provide the following date)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbldistrictsincharge',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '03000000000'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
