# Generated by Django 4.0.2 on 2022-03-13 18:59

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiu_gis', '0009_alter_poultryfarms_approval_construction_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldistrictsincharge',
            name='district_id',
            field=models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='spiu_gis.tbldistricts', verbose_name='District'),
        ),
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_establishment', models.CharField(max_length=255, null=True, verbose_name='Name of Establishment')),
                ('area_in_kanals', models.FloatField(blank=True, null=True, verbose_name='Area in Kanals')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Owner')),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(help_text='Latitude in Decimal Degree format upto 6 decimals like XX.XXXXXX, value would be between 25 to 40', null=True)),
                ('longitude', models.FloatField(help_text='Longitude in Decimal Degree format upto 6 decimals like XX.XXXXXX, value would be between 60 to 80', null=True)),
                ('approval_construction_phase', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Process', 'Under Process')], help_text='Environmental Approval for Construction Phase Obtained?, Date (if Yes, then provide the following date)', max_length=255, null=True)),
                ('construction_phase_approval_date', models.DateField(blank=True, help_text='approval date or in case of under process enter application date', null=True)),
                ('approval_operational_phase', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Process', 'Under Process')], help_text='Environmental Approval for Operation Phase Obtained, Date (if Yes, then provide the following date)', max_length=255, null=True)),
                ('operational_phase_approval_date', models.DateField(blank=True, help_text='operationla phase approval date or in case of under process enter application date', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('unique_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tblindustrycategory', verbose_name='Name of Category')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistricts', verbose_name='Name of District')),
                ('district_incharge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistrictsincharge', verbose_name='Name of District Incharge')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tblindustrymaincategory', verbose_name='Name of Main Category')),
            ],
            options={
                'verbose_name_plural': 'Establishments',
                'db_table': 'tbl_establishments',
                'managed': True,
            },
        ),
    ]
