# Generated by Django 4.0.2 on 2022-03-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0010_alter_tbldistrictsincharge_district_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultryfarms',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tblindustrycategory', verbose_name='Name of Category'),
        ),
        migrations.AlterField(
            model_name='tblindustrycategory',
            name='code',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
