# Generated by Django 4.0.2 on 2022-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiu_gis', '0011_poultryfarms_category_alter_tblindustrycategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblindustrycategory',
            name='capacity_unit',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Capacity Unit'),
        ),
    ]
