# Generated by Django 4.0.2 on 2023-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblGizData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'giz_data_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOrganizations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('intl', 'International'), ('govt', 'Government'), ('academia', 'Academia'), ('all', 'All')], max_length=255, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_level', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('child_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'giz_organizations',
                'managed': False,
            },
        ),
    ]
