# Generated by Django 4.0.2 on 2022-11-01 11:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

#
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spiu_gis', '0014_gpsdata_alter_poultryfarms_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLabAnalysisWasteWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id_no', models.CharField(max_length=254)),
                ('parameter', models.CharField(max_length=254)),
                ('peqs_limit', models.CharField(max_length=254, verbose_name='PEQS Limit')),
                ('concentration', models.FloatField(blank=True, null=True, verbose_name='Concentration/Results')),
                ('method_used', models.CharField(max_length=254, verbose_name='Method Used')),
                ('remarks', models.CharField(blank=True, choices=[('Complies PEQS', 'Complies PEQS'), ('Non Complies PEQS', 'Non Complies PEQS')], default='Complies PEQS', max_length=254, null=True)),
                ('remarks_calculated', models.CharField(blank=True, max_length=254, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('Water', 'Water'), ('Air', 'Air'), ('Noise', 'Noise')], max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Lab Analysis Waste Water',
                'verbose_name_plural': 'Lab Analysis Waste Water',
                'db_table': 'tbl_lab_analysis_waste_water',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLaboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=254)),
                ('officer_name', models.CharField(max_length=254)),
                ('designation', models.CharField(blank=True, choices=[('AD', 'Assistant Director (Lab)'), ('DD', 'Deputy Director (Lab)')], max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '03000000000'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('area_of_jurisdiction', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Laboratories Detail',
                'db_table': 'tbl_laboratories',
                'ordering': ['lab_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReportsWasteWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(default='Waste Water', max_length=254, verbose_name='Report Title')),
                ('letter_no', models.CharField(max_length=254, verbose_name='Letter No')),
                ('letter_date', models.DateField(verbose_name='Letter Date')),
                ('letter_issued_by', models.CharField(blank=True, max_length=254, null=True, verbose_name='Letter Issued By')),
                ('name_industry', models.CharField(max_length=254, verbose_name='Name of Industry')),
                ('address_industry', models.CharField(max_length=354, verbose_name='Address of Industry')),
                ('sample_type', models.CharField(choices=[('Grab', 'Grab'), ('Composite', 'Composite')], default='Grab', max_length=254, verbose_name='Sample Type')),
                ('sampling_point', models.CharField(default='Not Provided', max_length=254, verbose_name='Sampling Point')),
                ('treatment_facility', models.CharField(max_length=254, verbose_name='Treatment Facility')),
                ('treatment_facility_type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], max_length=254, verbose_name='Treatment Facility Type')),
                ('process_generating_wastewater', models.CharField(default='Not Provided', max_length=254, verbose_name='Process Generating Waste Water')),
                ('discharge', models.CharField(default='Not Provided', max_length=254)),
                ('sampling_date', models.DateField(verbose_name='Sample Date')),
                ('sample_receiving_date', models.DateField(blank=True, null=True, verbose_name='Date of Sample Receiving in Lab')),
                ('sample_id_no', models.CharField(max_length=254, verbose_name='Sample ID No')),
                ('sample_received_from', models.CharField(max_length=254, verbose_name='Sample Received From')),
                ('sample_received_by', models.CharField(max_length=254, verbose_name='Sample Received By')),
                ('form_d_path', models.FileField(upload_to='form_d', verbose_name='Form-D')),
                ('form_b_path', models.FileField(upload_to='form_b', verbose_name='Form-B')),
                ('letter_path', models.FileField(upload_to='letters', verbose_name='Letter')),
                ('latitude', models.FloatField(blank=True, help_text='up to 6 decimals between 25 to 40', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='up to 6 decimals between 60 to 80', null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Waste Water Report',
                'verbose_name_plural': 'Waste Water Reports',
                'db_table': 'tbl_reports_waste_water',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWasteWaterParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=254)),
                ('peqs_limit', models.CharField(max_length=254)),
                ('concentration', models.FloatField(blank=True, null=True, verbose_name='Concentration/Results')),
                ('method_used', models.CharField(max_length=254)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('Water', 'Water'), ('Air', 'Air'), ('Noise', 'Noise')], max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Report Parameters',
                'verbose_name_plural': 'Report Parameters',
                'db_table': 'tbl_waste_water_parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReportsAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(choices=[('Air', 'Air'), ('Noise', 'Surface Water'), ('Air and Noise', 'Air and Noise')], default='Air', max_length=254, verbose_name='Report Title')),
                ('report_no', models.CharField(max_length=254, verbose_name='Sample/Report No')),
                ('letter_no', models.CharField(max_length=254, verbose_name='Letter No')),
                ('letter_date', models.DateField(verbose_name='Letter Date')),
                ('letter_issued_by', models.CharField(blank=True, max_length=254, null=True, verbose_name='Letter Issued By')),
                ('name_industry', models.CharField(max_length=254, verbose_name='Name of Industry')),
                ('address_industry', models.CharField(max_length=354, verbose_name='Address of Industry')),
                ('sampling_source', models.CharField(default='Not Provided', max_length=254, verbose_name='Sampling/Emission Source')),
                ('monitoring_date', models.DateField(verbose_name='Monitoring Date')),
                ('fuel_type', models.CharField(default='Not Provided', max_length=254, verbose_name='Type of Fuel')),
                ('emission_control_system', models.CharField(default='Not Provided', max_length=254, verbose_name='Emission Control System')),
                ('sample_monitored_by', models.CharField(max_length=254, verbose_name='Sample Monitored By')),
                ('latitude', models.FloatField(blank=True, help_text='up to 6 decimals between 25 to 40', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='up to 6 decimals between 60 to 80', null=True)),
                ('form_d_path', models.FileField(blank=True, null=True, upload_to='form_d', verbose_name='Form-D')),
                ('form_b_path', models.FileField(blank=True, null=True, upload_to='form_b', verbose_name='Form-B')),
                ('letter_path', models.FileField(blank=True, null=True, upload_to='letters', verbose_name='Letter')),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tblindustrycategory', verbose_name='Name of Category')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spiu_gis.tbldistricts', verbose_name='Name of District from Address')),
                ('laboratory_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labs.tbllaboratories', verbose_name='Name of Laboratory')),
            ],
            options={
                'verbose_name': 'Air Quality Report',
                'verbose_name_plural': 'Air Quality Reports',
                'db_table': 'tbl_reports_air',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblLabAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id_no', models.CharField(blank=True, max_length=254, null=True)),
                ('parameter', models.CharField(max_length=254)),
                ('peqs_limit', models.CharField(max_length=254, verbose_name='PEQS Limit')),
                ('concentration', models.FloatField(blank=True, null=True, verbose_name='Concentration/Results')),
                ('method_used', models.CharField(max_length=254, verbose_name='Method Used')),
                ('remarks', models.CharField(blank=True, choices=[('Complies PEQS', 'Complies PEQS'), ('Non Complies PEQS', 'Non Complies PEQS')], default='Complies PEQS', max_length=254, null=True)),
                ('remarks_calculated', models.CharField(blank=True, max_length=254, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('Water', 'Water'), ('Air', 'Air'), ('Noise', 'Noise')], max_length=254, null=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labs.tblreportsair', verbose_name='Report ID')),
            ],
            options={
                'verbose_name': 'Lab Analysis',
                'verbose_name_plural': 'Lab Analysis',
                'db_table': 'tbl_lab_analysis',
                'managed': True,
            },
        ),
    ]
